# Generated by Django 4.2 on 2024-12-11 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='desc',
            new_name='description',
        ),
    ]
