# Generated by Django 4.2 on 2024-12-11 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protfolio', '0004_blogs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='tiemStamp',
            new_name='timeStamp',
        ),
    ]
