# Generated by Django 4.2 on 2024-12-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protfolio', '0005_rename_tiemstamp_blogs_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=15)),
                ('pkn', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=60)),
                ('college_name', models.CharField(max_length=100)),
                ('offer_status', models.CharField(max_length=50)),
                ('start_date', models.DateField(max_length=60)),
                ('end_date', models.DateField(max_length=60)),
                ('proj_report', models.CharField(max_length=60)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
