# Generated by Django 4.2 on 2024-12-11 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protfolio', '0007_rename_pkn_internship_usn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='internship',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='internship',
            name='fullname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='internship',
            name='proj_report',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='internship',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='internship',
            name='usn',
            field=models.CharField(max_length=20),
        ),
    ]
