# Generated by Django 4.2 on 2024-12-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protfolio', '0008_alter_internship_email_alter_internship_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='proj_report',
            field=models.TextField(blank=True, null=True),
        ),
    ]
